# Generated by Django 5.2.3 on 2025-07-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DareExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('profile', models.FileField(upload_to='')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_edited', models.BooleanField(default=False)),
                ('dare', models.TextField()),
            ],
        ),
    ]
