# Generated by Django 5.2.3 on 2025-07-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postdare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dare_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dare_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('time_limit', models.DateTimeField(blank=True, null=True)),
                ('category', models.TextField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='DareExchange',
        ),
    ]
