# Generated by Django 5.2.3 on 2025-08-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postdare', '0002_dare_project_delete_dareexchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='dare_project',
            name='difficulty',
            field=models.CharField(default='Moderate', max_length=10),
        ),
        migrations.AddField(
            model_name='dare_project',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dare_project',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dare_project',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
