# Generated by Django 5.2.3 on 2025-08-06 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postdare', '0004_dare_project_created_at_dare_project_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DareCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_notes', models.TextField()),
                ('proof_file', models.FileField(upload_to='dare_proofs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('dare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='postdare.dare_project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dare_completions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
